library(miniCRAN)
pdb <- pkgAvail(repos=c(CRAN="http://cran.revolutionanalytics.com"))
tags <- c("ggplot2","bitops","magrittr","stringi","RCurl","Rcpp","dplyr")
#pkgDep(tags, availPkgs = pdb)
dg <- makeDepGraph(tags, depends = TRUE,suggests = FALSE, availPkgs = pdb)
set.seed(1)
plot(dg, legendPosition = c(-1, -1), vertex.size=10, cex=0.7, main=NULL)